CREATE EXTENSION IF NOT EXISTS vector;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."task_status" AS ENUM('queued','provisioning','running','awaiting_user','paused','preparing_pr','pushing','creating_pr','pr_open','completed','cancelling','cancelled','failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" ("id" text PRIMARY KEY, "email" text NOT NULL, "name" text NOT NULL, "avatar_url" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON "users" ("email");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "organizations" ("id" text PRIMARY KEY, "slug" text NOT NULL, "name" text NOT NULL, "concurrency_limit" integer DEFAULT 4 NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_slug_unique" ON "organizations" ("slug");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "memberships" ("organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "role" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, PRIMARY KEY("organization_id","user_id"));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sessions" ("id" text PRIMARY KEY, "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "token_hash" text NOT NULL, "expires_at" timestamptz NOT NULL, "last_seen_at" timestamptz DEFAULT now() NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "sessions_token_hash_unique" ON "sessions" ("token_hash");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "accounts" ("id" text PRIMARY KEY, "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "provider" text NOT NULL, "provider_account_id" text NOT NULL, "encrypted_refresh_credential" text, "credential_key_version" integer, "expires_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "accounts_provider_identity_unique" ON "accounts" ("provider","provider_account_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "integration_accounts" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "user_id" text REFERENCES "users"("id") ON DELETE SET NULL, "kind" text NOT NULL, "external_account_id" text NOT NULL, "encrypted_credentials" text, "scopes" text[] DEFAULT ARRAY[]::text[] NOT NULL, "status" text DEFAULT 'active' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "github_installations" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "installation_id" bigint NOT NULL, "account_login" text NOT NULL, "status" text DEFAULT 'active' NOT NULL, "suspended_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "github_installation_external_unique" ON "github_installations" ("installation_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "repositories" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "github_installation_id" text REFERENCES "github_installations"("id") ON DELETE RESTRICT, "github_repository_id" bigint, "owner" text NOT NULL, "name" text NOT NULL, "full_name" text NOT NULL, "default_branch" text NOT NULL, "private" boolean DEFAULT true NOT NULL, "archived" boolean DEFAULT false NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "repositories_org_full_name_unique" ON "repositories" ("organization_id","full_name");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tasks" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "created_by_user_id" text NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT, "repository_id" text NOT NULL REFERENCES "repositories"("id") ON DELETE RESTRICT, "title" text NOT NULL, "objective" text NOT NULL, "status" task_status DEFAULT 'queued' NOT NULL, "version" integer DEFAULT 1 NOT NULL, "branch_name" text, "base_ref" text NOT NULL, "archived_at" timestamptz, "completed_at" timestamptz, "failure_code" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "tasks_org_status_idx" ON "tasks" ("organization_id","status");
CREATE INDEX IF NOT EXISTS "tasks_repo_created_idx" ON "tasks" ("repository_id","created_at");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "task_sessions" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "eve_session_id" text, "started_at" timestamptz DEFAULT now() NOT NULL, "ended_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "task_events" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "sequence" integer NOT NULL, "timestamp" timestamptz DEFAULT now() NOT NULL, "category" text NOT NULL, "phase" text NOT NULL, "status" text NOT NULL, "title" text NOT NULL, "what_was_done" text NOT NULL, "why_it_was_done" text NOT NULL, "evidence" jsonb DEFAULT '[]'::jsonb NOT NULL, "files_affected" jsonb DEFAULT '[]'::jsonb NOT NULL, "command" text, "tool_name" text, "verification" text, "risks" jsonb DEFAULT '[]'::jsonb NOT NULL, "next_step" text, "visibility" text DEFAULT 'user' NOT NULL, "correlation_id" text NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "task_events_sequence_unique" ON "task_events" ("task_id","sequence");
CREATE TABLE IF NOT EXISTS "task_plans" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "revision" integer NOT NULL, "objective" text NOT NULL, "confirmed_facts" jsonb DEFAULT '[]'::jsonb NOT NULL, "items" jsonb DEFAULT '[]'::jsonb NOT NULL, "verification_requirements" jsonb DEFAULT '[]'::jsonb NOT NULL, "risks" jsonb DEFAULT '[]'::jsonb NOT NULL, "change_reason" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "task_plans_revision_unique" ON "task_plans" ("task_id","revision");
CREATE TABLE IF NOT EXISTS "task_checkpoints" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "kind" text NOT NULL, "payload" jsonb NOT NULL, "event_sequence" integer NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workspaces" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "provider" text NOT NULL, "provider_workspace_id" text NOT NULL, "status" text NOT NULL, "resource_limits" jsonb NOT NULL, "last_heartbeat_at" timestamptz, "expires_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "workspaces_task_unique" ON "workspaces" ("task_id");
CREATE TABLE IF NOT EXISTS "workspace_snapshots" ("id" text PRIMARY KEY, "workspace_id" text NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "provider_snapshot_id" text NOT NULL, "reason" text NOT NULL, "size_bytes" bigint, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "codex_threads" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "workspace_id" text NOT NULL REFERENCES "workspaces"("id") ON DELETE RESTRICT, "provider_thread_id" text NOT NULL, "model" text NOT NULL, "provider_config_version" integer NOT NULL, "last_processed_event_sequence" integer DEFAULT 0 NOT NULL, "last_confirmed_completion_status" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "codex_threads_task_unique" ON "codex_threads" ("task_id");
CREATE TABLE IF NOT EXISTS "codex_turns" ("id" text PRIMARY KEY, "codex_thread_id" text NOT NULL REFERENCES "codex_threads"("id") ON DELETE CASCADE, "provider_turn_id" text, "status" text NOT NULL, "started_at" timestamptz DEFAULT now() NOT NULL, "completed_at" timestamptz, "error_classification" text);
CREATE TABLE IF NOT EXISTS "tool_calls" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "codex_turn_id" text REFERENCES "codex_turns"("id") ON DELETE CASCADE, "tool_name" text NOT NULL, "status" text NOT NULL, "summary" text NOT NULL, "started_at" timestamptz DEFAULT now() NOT NULL, "completed_at" timestamptz, "duration_ms" integer, "correlation_id" text NOT NULL);
CREATE TABLE IF NOT EXISTS "command_runs" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "tool_call_id" text REFERENCES "tool_calls"("id") ON DELETE SET NULL, "command" text NOT NULL, "working_directory" text NOT NULL, "status" text NOT NULL, "exit_code" integer, "output_object_key" text, "started_at" timestamptz DEFAULT now() NOT NULL, "completed_at" timestamptz, "duration_ms" integer);
CREATE TABLE IF NOT EXISTS "file_changes" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "path" text NOT NULL, "previous_path" text, "status" text NOT NULL, "additions" integer DEFAULT 0 NOT NULL, "deletions" integer DEFAULT 0 NOT NULL, "patch_object_key" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "artifacts" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "name" text NOT NULL, "mime_type" text NOT NULL, "object_key" text NOT NULL, "size_bytes" bigint NOT NULL, "checksum" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "pull_requests" ("id" text PRIMARY KEY, "task_id" text NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "github_repository_id" bigint, "number" integer, "branch_name" text NOT NULL, "title" text NOT NULL, "state" text NOT NULL, "url" text, "head_sha" text, "mergeable" boolean, "review_state" text, "idempotency_key" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "pull_requests_task_unique" ON "pull_requests" ("task_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "skills" ("id" text PRIMARY KEY, "organization_id" text REFERENCES "organizations"("id") ON DELETE CASCADE, "owner_user_id" text REFERENCES "users"("id") ON DELETE CASCADE, "slug" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "visibility" text DEFAULT 'private' NOT NULL, "disabled_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "skill_versions" ("id" text PRIMARY KEY, "skill_id" text NOT NULL REFERENCES "skills"("id") ON DELETE CASCADE, "version" integer NOT NULL, "checksum" text NOT NULL, "object_key" text NOT NULL, "frontmatter" jsonb NOT NULL, "requested_capabilities" jsonb DEFAULT '[]'::jsonb NOT NULL, "published_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "skill_versions_number_unique" ON "skill_versions" ("skill_id","version");
CREATE TABLE IF NOT EXISTS "skill_assignments" ("id" text PRIMARY KEY, "skill_version_id" text NOT NULL REFERENCES "skill_versions"("id") ON DELETE CASCADE, "scope_type" text NOT NULL, "scope_id" text NOT NULL, "enabled" boolean DEFAULT true NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "skill_assignments_scope_unique" ON "skill_assignments" ("skill_version_id","scope_type","scope_id");
CREATE TABLE IF NOT EXISTS "memories" ("id" text PRIMARY KEY, "scope_type" text NOT NULL, "scope_id" text NOT NULL, "kind" text NOT NULL, "content" text NOT NULL, "summary" text NOT NULL, "embedding" vector(1536), "source_task_id" text REFERENCES "tasks"("id") ON DELETE SET NULL, "expires_at" timestamptz, "deleted_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "memories_scope_idx" ON "memories" ("scope_type","scope_id");
CREATE TABLE IF NOT EXISTS "schedules" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "kind" text NOT NULL, "schedule" text NOT NULL, "timezone" text NOT NULL, "payload" jsonb NOT NULL, "enabled" boolean DEFAULT true NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "notifications" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "user_id" text REFERENCES "users"("id") ON DELETE CASCADE, "task_id" text REFERENCES "tasks"("id") ON DELETE CASCADE, "channel" text NOT NULL, "status" text NOT NULL, "payload" jsonb NOT NULL, "idempotency_key" text NOT NULL, "sent_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "notifications_idempotency_unique" ON "notifications" ("idempotency_key");
CREATE TABLE IF NOT EXISTS "webhook_deliveries" ("id" text PRIMARY KEY, "provider" text NOT NULL, "delivery_id" text NOT NULL, "signature_valid" boolean NOT NULL, "event_type" text NOT NULL, "status" text NOT NULL, "received_at" timestamptz DEFAULT now() NOT NULL, "processed_at" timestamptz, "error_classification" text);
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_deliveries_provider_unique" ON "webhook_deliveries" ("provider","delivery_id");
CREATE TABLE IF NOT EXISTS "idempotency_keys" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "scope" text NOT NULL, "key" text NOT NULL, "request_hash" text NOT NULL, "response" jsonb, "expires_at" timestamptz NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "idempotency_keys_scope_unique" ON "idempotency_keys" ("organization_id","scope","key");
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE RESTRICT, "actor_type" text NOT NULL, "actor_id" text, "action" text NOT NULL, "target_type" text NOT NULL, "target_id" text NOT NULL, "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL, "correlation_id" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "audit_logs_org_time_idx" ON "audit_logs" ("organization_id","created_at");
CREATE TABLE IF NOT EXISTS "usage_records" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE, "user_id" text REFERENCES "users"("id") ON DELETE SET NULL, "task_id" text REFERENCES "tasks"("id") ON DELETE SET NULL, "kind" text NOT NULL, "quantity" bigint NOT NULL, "unit" text NOT NULL, "recorded_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "oauth_authorization_states" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "provider" text NOT NULL, "state_hash" text NOT NULL, "encrypted_verifier" text NOT NULL, "nonce_hash" text NOT NULL, "redirect_uri" text NOT NULL, "expires_at" timestamptz NOT NULL, "consumed_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "oauth_state_hash_unique" ON "oauth_authorization_states" ("state_hash");
CREATE TABLE IF NOT EXISTS "outbox" ("id" text PRIMARY KEY, "aggregate_type" text NOT NULL, "aggregate_id" text NOT NULL, "event_type" text NOT NULL, "payload" jsonb NOT NULL, "attempts" integer DEFAULT 0 NOT NULL, "available_at" timestamptz DEFAULT now() NOT NULL, "processed_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS "outbox_available_idx" ON "outbox" ("processed_at","available_at");
